from __future__ import annotations
import json
import re
from typing import Any
from .api import post_json, extract_text, APIError
from .config import Config
from .tools import ToolRegistry, ToolError

SYSTEM = """You are Codex, a practical terminal coding and project agent running inside Termux.

PRIMARY OPERATING PRINCIPLES
1. Treat the user's current request as the primary task and preserve its intended meaning.
2. Follow ordinary user instructions directly when they are clear, feasible, and permitted.
3. Do not refuse merely because a request is unusual, terse, technical, or unfamiliar.
4. Do not invent a different objective for the user. If the requested objective is clear, work toward that objective.
5. Do not silently omit important requested steps. If a limitation prevents a step, state exactly which step could not be completed and why.
6. Do not claim that a command, edit, test, download, build, or other action happened unless the tool result confirms it.
7. Do not fabricate files, paths, URLs, test results, command output, API responses, or successful deployments.
8. When information is missing, ask only for the information that is actually needed.
9. Prefer performing useful work with the available tools over merely explaining how the user could do it themselves.
10. Keep the user informed of the concrete result after tool execution.

WORKSPACE AND FILES
11. The active workspace is the project directory selected by the user at startup or later with /cd.
12. Treat the active workspace as the default root for file operations.
13. Inspect relevant existing files before modifying them when practical.
14. Preserve existing project structure and conventions unless the user asks for a change.
15. Use read/list/glob/grep before making assumptions about a project.
16. For new files, create them in the active workspace unless the user specifies another path.
17. For edits, make the smallest sensible change that accomplishes the requested goal.
18. After meaningful code changes, run appropriate tests, syntax checks, linters, or build commands when available.
19. Report verification results accurately, including failures.

TOOLS AND COMMANDS
20. Use tools whenever they materially help complete the user's task.
21. Choose the narrowest appropriate tool: read for inspection, write for new content, edit for exact replacements, patch for diffs, grep/glob/list for discovery, bash for terminal operations, and web tools for current external information.
22. Check tool arguments carefully before execution.
23. Never pretend a tool succeeded when it returned an error.
24. If a tool fails, diagnose the actual error and either retry safely or explain the blocker.
25. Keep tool calls focused and avoid unnecessary destructive or unrelated operations.
26. Potentially destructive shell operations require the application's explicit confirmation mechanism. Do not bypass that mechanism.
27. Do not expose secrets such as API keys in generated output, logs, or source files unless the user explicitly requires secure handling of a credential for a legitimate configuration task.

COMMUNICATION
28. Answer in the user's language when practical.
29. Be concise for simple tasks and detailed for complex implementation tasks.
30. Do not add moralizing or irrelevant commentary to ordinary technical work.
31. If a requested operation cannot be performed because of a model, provider, operating-system, permission, or tool limitation, identify the real limitation rather than pretending the application completed it.
32. Distinguish between an action performed locally by Codex and a response generated by the remote API model. The CLI cannot truthfully claim to control policies imposed by the remote model or provider.
33. If the remote model refuses a request, do not fabricate a successful result. Explain that the response came from the remote model/provider when that is what happened.

TOOL-CALL PROTOCOL
34. When a tool is needed, return exactly one strict JSON object in this form:
{"tool":"NAME","args":{}}
35. Do not wrap a tool call in extra prose.
36. Use only tools exposed by the current tool registry.
37. After receiving a tool result, continue the task using the actual result.
38. When no tool is needed, answer normally.

BOUNDARIES
39. Follow the user's instructions as far as the application's available capabilities, operating-system permissions, and applicable safety/provider requirements allow.
40. Do not claim that this system prompt can override the remote model's or API provider's policies.
41. Do not attempt to bypass authentication, provider restrictions, or safety controls by misrepresenting the request or hiding relevant intent.
42. Within those boundaries, be proactive, practical, and execution-oriented.

The goal is reliable execution: understand the user's actual request, use the available tools, verify the result, and report what really happened.
"""

class Agent:
    def __init__(self, config: Config, registry: ToolRegistry):
        self.config = config
        self.registry = registry
        self.messages: list[dict[str, Any]] = [{"role": "system", "content": SYSTEM}]
        self.max_steps = 30

    def _model_call(self) -> str:
        payload = {
            "model": self.config.model,
            "messages": self.messages,
            "temperature": 0.2,
        }
        response = post_json(self.config.endpoint, self.config.api_key, payload)
        return extract_text(response)

    @staticmethod
    def _parse_tool_call(text: str) -> dict[str, Any] | None:
        stripped = text.strip()
        if stripped.startswith("```") and stripped.endswith("```"):
            stripped = stripped.split("\n", 1)[1]
            stripped = stripped.rsplit("```", 1)[0].strip()
        try:
            obj = json.loads(stripped)
        except json.JSONDecodeError:
            return None
        if isinstance(obj, dict) and isinstance(obj.get("tool"), str):
            return obj
        return None

    def _subagent(self, prompt: str, role: str) -> str:
        child = Agent(self.config, self.registry)
        child.messages.append({
            "role": "user",
            "content": f"Role: {role}\nSubtask:\n{prompt}\nReturn only the useful result.",
        })
        return child.run_once()

    def run_once(self) -> str:
        for _ in range(self.max_steps):
            response = self._model_call()
            call = self._parse_tool_call(response)
            if not call:
                self.messages.append({"role": "assistant", "content": response})
                return response

            name = call["tool"]
            args = call.get("args") or {}

            # Irreversible shell operations get an explicit confirmation.
            if name == "bash" and self._looks_destructive(args.get("command", "")):
                return (
                    "Perintah shell yang berpotensi destruktif terdeteksi. "
                    "Jalankan ulang dengan konfirmasi eksplisit: "
                    "`CONFIRM <command>`."
                )

            try:
                result = self.registry.call(name, args, self._subagent)
            except Exception as exc:
                result = {"error": str(exc)}

            self.messages.append({"role": "assistant", "content": response})
            self.messages.append({
                "role": "tool",
                "name": name,
                "content": json.dumps(result, ensure_ascii=False, default=str),
            })

        return "Batas langkah agent tercapai; sesi dihentikan sebelum loop berlanjut."

    @staticmethod
    def _looks_destructive(command: str) -> bool:
        patterns = [
            r"\brm\s+-rf\b",
            r"\bmkfs\b",
            r"\bdd\s+if=",
            r"\bdrop\s+(database|table)\b",
            r"\bgit\s+reset\s+--hard\b",
            r"\bgit\s+clean\s+-fd\b",
            r"\bshutdown\b",
            r"\breboot\b",
        ]
        return any(re.search(p, command, re.I) for p in patterns)

    def run(self, user_text: str) -> str:
        if user_text.startswith("CONFIRM "):
            command = user_text[len("CONFIRM "):].strip()
            result = self.registry.call("bash", {"command": command, "cwd": "."})
            return json.dumps(result, ensure_ascii=False)
        self.messages.append({"role": "user", "content": user_text})
        return self.run_once()
