from __future__ import annotations
import os
import shutil
import sys
import subprocess
import base64
import termios
import tty
from .config import Config, normalize_base_url, load_saved_config, save_config, update_api_key, has_saved_config
from .tools import Workspace
from .project import ProjectIndex
from .renderer import render_markdown, LiveMarkdownRenderer, extract_code_blocks

RED = "\033[91m"
CYAN = "\033[96m"
DIM = "\033[2m"
RESET = "\033[0m"
CLEAR = "\033[2J\033[H"

def clear():
    print(CLEAR, end="")


def restore_terminal():
    """Restore normal terminal line discipline without alternate-screen mode."""
    if not sys.stdin.isatty():
        return
    try:
        fd = sys.stdin.fileno()
        attrs = termios.tcgetattr(fd)
        attrs[3] |= termios.ICANON | termios.ECHO
        attrs[3] |= termios.ISIG
        termios.tcsetattr(fd, termios.TCSADRAIN, attrs)
        sys.stdout.write("\033[0m")
        sys.stdout.flush()
    except (OSError, termios.error):
        pass

def mask_key(key: str) -> str:
    if len(key) <= 8:
        return "*" * len(key)
    return key[:4] + "*" * (len(key) - 8) + key[-4:]


def masked_input(prompt: str) -> str:
    """Read a secret from a Termux TTY while displaying * for each character.

    Unlike getpass(), this uses the active terminal file descriptor directly,
    which is more reliable with Android/Termux keyboards and paste events.
    It also restores terminal settings on every exit path.
    """
    if not sys.stdin.isatty():
        return input(prompt)

    sys.stdout.write(prompt)
    sys.stdout.flush()
    fd = sys.stdin.fileno()
    old = termios.tcgetattr(fd)
    chars = []
    try:
        tty.setraw(fd)
        while True:
            ch = os.read(fd, 1).decode("utf-8", errors="ignore")
            if not ch:
                continue
            code = ord(ch)
            if ch in ("\r", "\n"):
                sys.stdout.write("\r\n")
                sys.stdout.flush()
                return "".join(chars)
            if code in (3, 4):  # Ctrl-C / Ctrl-D
                raise KeyboardInterrupt
            if ch in ("\x7f", "\b"):
                if chars:
                    chars.pop()
                    sys.stdout.write("\b \b")
                    sys.stdout.flush()
                continue
            if code == 27:
                # Ignore terminal escape sequences generated by special keys.
                # A plain ESC clears the current secret for convenience.
                nxt = os.read(fd, 1).decode("utf-8", errors="ignore")
                if nxt == "[":
                    while True:
                        part = os.read(fd, 1).decode("utf-8", errors="ignore")
                        if not part or "@A-Za-z~".find(part) >= 0:
                            break
                else:
                    chars.clear()
                    sys.stdout.write("\r" + " " * (len(prompt) + len(chars) + 2) + "\r" + prompt)
                    sys.stdout.flush()
                continue
            # Ignore other C0 control characters but accept normal Unicode bytes.
            if code < 32:
                continue
            chars.append(ch)
            sys.stdout.write("*")
            sys.stdout.flush()
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old)

def setup() -> Config:
    """First run collects credentials; later runs reuse global ~/.codex/config.json."""
    clear()
    workspace = os.path.abspath(os.environ.get("CODEX_WORKSPACE", os.getcwd()))
    saved = load_saved_config(workspace)
    if saved is not None:
        print("Codex config tersimpan ditemukan.\n")
        return saved

    print("Codex setup pertama kali\n")
    while True:
        try:
            base = normalize_base_url(input("Base url: "))
            break
        except ValueError as exc:
            print(f"{RED}Error:{RESET} {exc}")
    key = masked_input("api key: ").strip()
    model = input("id model: ").strip()
    if not key or not model:
        raise ValueError("API key dan model wajib diisi.")
    try: temperature = max(0.0, min(1.0, float(os.environ.get("CODEX_TEMPERATURE", "0.15"))))
    except ValueError: temperature = 0.15
    stream = os.environ.get("CODEX_STREAM", "1").lower() not in {"0", "false", "no"}
    config = Config(base, key, model, workspace, max_tokens=None, temperature=temperature, stream=stream)
    return config


def edit_api_key(config: Config) -> bool:
    clear()
    print("Edit API key\n")
    new_key = masked_input("api key baru: ").strip()
    if not new_key:
        print(f"{RED}Error:{RESET} API key tidak boleh kosong.\n")
        return False
    update_api_key(new_key)
    config.api_key = new_key
    print(f"{CYAN}API key tersimpan.\n{RESET}")
    return True

def verify(config: Config, api_call):
    clear()
    print("Verifikasi api: loading...", flush=True)
    try:
        api_call()
    except Exception as exc:
        print(f"{RED}Verifikasi gagal:{RESET} {exc}")
        raise SystemExit(1)
    print(f"{CYAN}Verifikasi api: berhasil.{RESET}")

def choose_workspace() -> str:
    """Prompt for the folder Codex should operate in, then return an absolute path."""
    while True:
        raw = input("Path folder: ").strip()
        if not raw:
            print(f"{RED}Error:{RESET} Path folder wajib diisi.")
            continue
        candidate = os.path.abspath(os.path.expanduser(raw))
        if not os.path.isdir(candidate):
            print(f"{RED}Error:{RESET} Folder tidak ditemukan: {candidate}")
            continue
        try:
            os.chdir(candidate)
        except OSError as exc:
            print(f"{RED}Error:{RESET} Tidak bisa masuk ke folder: {exc}")
            continue
        print(f"Path folder: {candidate}")
        print(f"{CYAN}Workspace aktif. Membuka Codex...{RESET}\n")
        return candidate

def banner(config: Config):
    BLACK='\033[40m'; REDB='\033[91m'
    print(REDB + BLACK + r"""
     ██╗ █████╗  ██████╗██╗  ██╗
     ██║██╔══██╗██╔════╝██║ ██╔╝
     ██║███████║██║     █████╔╝ 
██   ██║██╔══██║██║     ██╔═██╗ 
╚█████╔╝██║  ██║╚██████╗██║  ██╗
 ╚════╝ ╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝
""" + RESET)
    cols=min(shutil.get_terminal_size((80,24)).columns,100)
    print("\n"+"─"*cols+"\n")


def _change_workspace(agent, config, registry, raw_path: str):
    raw_path = raw_path.strip()
    if not raw_path:
        return "Workspace saat ini: " + str(registry.ws.root)
    candidate = os.path.abspath(os.path.expanduser(raw_path))
    if not os.path.isdir(candidate):
        return f"Workspace tidak ditemukan atau bukan direktori: {candidate}"
    os.chdir(candidate)
    registry.ws = Workspace(candidate)
    registry.config = config
    registry.memory = __import__('codex.memory', fromlist=['MemoryStore']).MemoryStore(candidate)
    registry.project = ProjectIndex(candidate)
    registry.checkpoints = __import__('codex.checkpoint', fromlist=['Checkpoints']).Checkpoints(candidate)
    registry.project.scan()
    config.workspace = candidate
    agent.project_context = registry.project.compact_context()
    agent.messages.append({
        "role": "system",
        "content": f"Workspace aktif sekarang: {candidate}. Gunakan workspace ini untuk operasi file dan shell. Project context baru:\n{agent.project_context}",
    })
    return f"Workspace aktif: {candidate}"

def copy_text_to_clipboard(text: str) -> str:
    """Copy text using Termux API when available, otherwise OSC52."""
    exe = shutil.which("termux-clipboard-set")
    if exe:
        proc = subprocess.run([exe], input=text, text=True, capture_output=True, timeout=10)
        if proc.returncode == 0:
            return "Code berhasil disalin ke clipboard Termux."
    encoded = base64.b64encode(text.encode("utf-8")).decode("ascii")
    sys.stdout.write(f"\033]52;c;{encoded}\a")
    sys.stdout.flush()
    return "Kode dikirim ke clipboard terminal via OSC52 (jika terminal mendukungnya)."


def run_ui(agent, config, registry):
    import atexit
    atexit.register(restore_terminal)
    clear()
    banner(config)
    last_answer = ""
    while True:
        try:
            text = input(f"{RED}root@codex:~#{RESET} ").strip()
        except (EOFError, KeyboardInterrupt):
            restore_terminal()
            clear()
            break
        if not text:
            continue
        if text in {"/exit", "/quit"}:
            restore_terminal()
            clear()
            break
        if text == "/edit":
            edit_api_key(config)
            banner(config)
            continue
        if text == "/clear":
            agent.messages = [{"role":"system","content":agent.messages[0]["content"]}]
            clear(); banner(config); continue
        if text == "/new":
            from .memory import MemoryStore
            registry.memory = MemoryStore(str(registry.ws.root))
            agent.registry.memory = registry.memory
            agent.messages = [{"role":"system","content":agent.messages[0]["content"]}]
            agent.execution_reminders = 0
            agent.request_count = 0
            agent.last_usage = {}
            agent.last_rate_limits = {}
            last_answer = ""
            clear(); banner(config)
            print(f"{DIM}Session baru dimulai. Memori percakapan sebelumnya tidak digunakan.{RESET}\n")
            continue
        if text == "/pwd":
            print(f"Workspace: {registry.ws.root}\n")
            continue
        if text.startswith("/copy"):
            parts=text.split(maxsplit=1)
            try: idx=int(parts[1]) if len(parts)>1 else 1
            except ValueError: idx=1
            blocks=extract_code_blocks(last_answer)
            if not blocks or idx < 1 or idx > len(blocks):
                print(f"{RED}Code block tidak ditemukan: {idx}{RESET}\n")
                continue
            print(copy_text_to_clipboard(blocks[idx-1]["code"]) + "\n")
            continue
        if text.startswith("/cd"):
            target = text[3:].strip()
            print(_change_workspace(agent, config, registry, target) + "\n")
            continue
        try:
            print(f"{CYAN}root@ai-codex:~#{RESET}")
            print(f"{DIM}⠿ Jack sedang berpikir...{RESET}", flush=True)
            streamed=[]
            def on_token(piece): streamed.append(piece)
            agent.stream_callback = on_token
            try:
                answer = agent.run(text)
            finally:
                agent.stream_callback = None
            last_answer = "".join(streamed) if streamed else answer
            print("\r\033[2K", end="")
            print(render_markdown(last_answer))
            stats=agent.runtime_stats(); usage=stats.get("usage") or {}
            extra=f"request {stats.get('requests',0)}"
            if usage.get("total_tokens") is not None: extra += f" · tokens {usage['total_tokens']}"
            if stats.get("last_latency_ms"): extra += f" · {stats['last_latency_ms']} ms avg"
            limits=stats.get("rate_limits") or {}
            remaining_req=next((v for k,v in limits.items() if "remaining-requests" in k.lower()), None)
            remaining_tok=next((v for k,v in limits.items() if "remaining-tokens" in k.lower()), None)
            if remaining_req is not None: extra += f" · req left {remaining_req}"
            if remaining_tok is not None: extra += f" · tok left {remaining_tok}"
            print(f"{DIM}[{extra}]{RESET}\n")
        except KeyboardInterrupt:
            restore_terminal()
            clear()
            break
        except Exception as exc:
            print(f"{RED}API/tool error:{RESET} {exc}\n")
